### ISSUE TITLE
not enough values in test

### ISSUE THREAD

**Issue by vcvishal** [DeepTrial/Optic-Disc-Unet#5]
Traceback (most recent call last):
  File "main_test.py", line 40, in <module>
    main_test()
  File "main_test.py", line 28, in main_test
    infer.predict()
  File "C:\Users\vcvis\Desktop\Optic-Disc-Unet-master\perception\infers\segmention_infer.py", line 51, in predict
    _, contours, _ = cv2.findContours(binaryResult, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

please help 
thank you

**Comment by vcvishal** [comment]
problem has solved

**Comment by icsamir** [comment]
> Traceback (most recent call last):
> File "main_test.py", line 40, in
> main_test()
> File "main_test.py", line 28, in main_test
> infer.predict()
> File "C:\Users\vcvis\Desktop\Optic-Disc-Unet-master\perception\infers\segmention_infer.py", line 51, in predict
> _, contours, _ = cv2.findContours(binaryResult, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: not enough values to unpack (expected 3, got 2)
> 
> please help
> thank you

how did you solve it?
I have the same problem
